### ISSUE TITLE
Freenet should be removed from Block List

### ISSUE THREAD

**Issue by Zodiac1978** [Trumani/stop-spammers#150]
At least in Germany this is an [telecommunication provider](https://www.freenet.de) which is also providing email-addresses. If someone tries to register which such a email address it is blocked.

This line should be removed: https://github.com/Trumani/stop-spammers/blob/7bbfdef18aa46bb0d660732bae11624c5fc7f89b/classes/ss_get_options.php#L278

Thanks for considering!

All the best
Torsten

**Comment by bhadaway** [comment]
Hi Torsten,

This wouldn't have been added if it wasn't abused for spam.

It should remain blocked by default, but if a specific site, especially one in Germany needs to allow it, they can simply remove it from spam words list.

Thanks

**Comment by Zodiac1978** [comment]
> It should remain blocked by default, but if a specific site, especially one in Germany needs to allow it, they can simply remove it from spam words list.

It took me hours to find out this issue and I am a web developer.

If there are users from Germany they will not took this route I'm afraid. This registration will be blocked and frustrate the users or the plugin will be replaced. I don't think every one will check why all those registrations fail ...

Best,
Torsten

**Comment by bhadaway** [comment]
You're not wrong, but the issue you bring up is the entire nature of the plugin. It's an aggressive plugin and there will always be false positives. Unblocking Freenet might be useful to a small percentage of users, but cause more spam for the majority of users. It's a delicate balance and every site will have to be fine-tuned differently.

**Comment by Zodiac1978** [comment]
It is your decision. I'm sure you have your reasons and data to prove it. But I have mine as well and therefore don't like this direction:

> It's an aggressive plugin and there will always be false positives. Unblocking Freenet might be useful to a small percentage of users, but cause more spam for the majority of users.

False positives are a no go. And your explanation is very thin:
> This wouldn't have been added if it wasn't abused for spam.

You are banning a whole group with this - at least in Germany - and therefore I rated your plugin accordingly.

**Comment by bhadaway** [comment]
Hi Torsten,

There will always be false positives with this and every other spam/security/anti-virus solution in existence; there's no getting around that, there never was, and there never will be.

Even if we removed Freenet from the spam list, that would still be true. Even you would still get false positives and have to whitelist users.

You're of course entitled to your opinion, but I wanted make sure to be very clear about the facts here, because if false positives are an absolute no-go for you, that means that you won't be able to use Stop Spammers, Wordfence, or any other security measure really.

You would just need to leave your site wide open so that no one ever got blocked and then take on a different approach, where you just manually clean up spam comments and users. Within reason, that's actually a viable solution. Some people really do manage blogs, forums, email, etc. like that, including myself for some smaller projects.

If you don't have the time or your site is too big to practically manage that, there are many different kinds of layers you can add to help keep the spam down. Like I said, false positives are inevitable no matter what, but the goal is essentially _less_ false positives. That requires fine-tuning.

Stop Spammers is great for that, but if you find that the plugin is too aggressive and you don't want to have to deal with all those settings, there are some less aggressive, but still effective solutions.

I really like the work of Jeff Starr:

https://perishablepress.com/tag/blacklist/

He's come up with some awesome hands-free solutions like the 7G Firewall:

https://perishablepress.com/7g-firewall/

No plugin or settings required; just add it to your .htaccess file and done. I recommend adding it whether you decide to keep Stop Spammers or not.

I'm sorry if the answer I've provided you isn't the one you want to hear, but it's the best and most honest one I can offer. I wish you good luck in fighting spam.

Thanks
