### ISSUE TITLE
Number of periods in email's domain

### ISSUE THREAD

**Issue by mnakalay** [Trumani/stop-spammers#165]
in chkperiods.php you are checking the number of periods "." to be >= 2 to decide it's spammy.

Any legitimate email address with .co.uk for instance or .co.au will be flagged as spammy.

I think it should be > 2 and not >= 2

**Comment by bhadaway** [comment]
The vast majority of subdomain email address spammers that have emerged have just 2 periods. If it was 3 or higher, the check might as well not even exist. Right now, it's an optional feature that is useful to most users.

If you have the rare occasion of a legitimate user getting caught in the spam filter, they can be manually approved. If it's much more frequent, say because you live in a country where 2 period email addresses are common, you should disable the check altogether.

**Comment by bhadaway** [comment]
Update, in a future update, I think we'll just exclude the TLD altogether and just check for subdomains, which should kill two birds with one stone.
