### ISSUE TITLE
block user account creation with certain email

### ISSUE THREAD

**Issue by ZeroWasteIngi** [Trumani/stop-spammers#167]
hi there,

I've installed stop-spammers to block a spammer who's constantly creating new user accounts on my website with an demo.com email address. I had hoped this would help:
<img width="412" alt="stopspammers" src="https://user-images.githubusercontent.com/28537974/105476391-dd2a6d00-5ca0-11eb-8e7d-930f71c95e66.png">

But I can still create users with an email address ending in demo.com. Do you have an idea for me how I can block this?

**Comment by ZeroWasteIngi** [comment]
I've uninstalled the plugin because it kicked me out of my webshop and didn't allow me back in.

**Comment by bhadaway** [comment]
Hmm, there are a few issues that come to mind immediately:

1. When testing a new block feature, you don't want to use your normal IP that's the same as the IP that's already been whitelisted for your account, as that will generally not work or give an accurate reading.
2. If you ended up getting locked out of your account, maybe the block actually did work?

If you'd like to keep using Stop Spammers, make sure to see the FAQs, especially the bit about what to do if you lock yourself out of your site:

https://github.com/Trumani/stop-spammers/wiki/FAQs

Then, rather than testing blocks yourself again, instead, just wait a few days and see of the specific spam you're trying to block slows down or stops.

If you'd rather not wait and want to do testing yourself, I can offer you some tips; just let me know.
